### ISSUE TITLE
失效了？

### ISSUE THREAD

**Issue by Lim-CN** [xe5700/genshin-impact-bbs-soulsign#1]
![image](https://user-images.githubusercontent.com/60124911/99878219-d2bb0b00-2c3e-11eb-958b-4013dead4d03.png)

**Comment by longhuan1999** [comment]
我也是这样，几天前开始的，一直这样

**Comment by xe5700** [comment]
新版本修改了签到验证方式懒得改弃坑了，用https://github.com/y1ndan/genshin-impact-helper 这个项目。
